### ISSUE TITLE
iTermなどSixel対応のターミナルが推奨と明示したほうがよいのでは

### ISSUE THREAD

**Issue by mizmiz1229** [otiai10/amesh#15]
折角Sixel対応のターミナルだと綺麗に画像が表示されるのだから、推奨環境についての一文があればよいと思う。macのデフォルトのターミナルで実行すると、画像が荒いため、ユーザーが離脱してしまうのではないか。

# 再現手順

bash-3.2$ amesh

# 期待される結果
サンプル画像を提示するだけではなく、iTermなどSixel対応のターミナルを推奨する文章がReadMeに一言ほしい。

# 実際の結果
荒い画像が出て一目でわからなかった

# 自分の環境
Mac OS X 10.13.4 x64
go version go1.10.3 darwin/amd64
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

**Comment by otiai10** [comment]
長らく対応してなくてすみません。これに関しては正直自分では現状で十分だと思っているので、pull-reqなど投げていただけるとうれしいです。
CC https://github.com/oss-gate/workshop/issues/949
