### ISSUE TITLE
go get時にインストールの成功を確認できる方が良いのでは

### ISSUE THREAD

**Issue by mizmiz1229** [otiai10/amesh#16]
goを扱っている人であれば、go getのコマンドの実行後に何も出なければ正常であるとわかる。しかし、やったことがない人は正常にインストールできたかどうかを知りたい。
goに疎いユーザが使うときに一言メッセージが出ると安心できると思います。

# 再現手順
goがないのでgoをインストールする
Goの公式サイトにアクセスした
https://golang.org/doc/install

Install the Go toolsを押下

https://golang.org/dl/
から　
go1.11.darwin-amd64.pkg
をダウンロードした

インストラーをクリックしてインストールできた。

$ go get github.com/otiai10/amesh/amesh
$

応答がないので再度実行した

$ go get github.com/otiai10/amesh/amesh
$

# 期待される結果
successなど表示される

# 実際の結果
何も表示されない

# 自分の環境
Mac OS X 10.13.4 x64
go version go1.10.3 darwin/amd64

**Comment by otiai10** [comment]
たしかに、

```
go get -u -v github.com/otiai10/amesh/amesh
```

とするべきでしたね。
CC https://github.com/oss-gate/workshop/issues/949
